### ISSUE TITLE
only sensors

### ISSUE THREAD

**Issue by jaeuwi74** [shprota/home_assistant_crow#2]
Hello,
thanks for the share but have only sensors, no alarm panel or security sensors ?

**Comment by shprota** [comment]
The alarm panel should be there. As for the security sensors, the current Crow public protocol does not expose their readings.

**Comment by jaeuwi74** [comment]
THANKS,
I found it in the developer tool.
but it's really a shame for the binary sensors.
sensor images?
I'm not a developer.
but I'm sure you'll find a trick 
THANKS
